Repository marcosurbanski/urbpy, pull requests merged in 2025-07, with the labels that each got.

#252 90
  Pipfile
  Pipfile.lock
  pypro/aperitivos/migrations/0002_alter_video_slug.py
  pypro/base/tests/test_home.py
  pypro/base/views.py
  pypro/modulos/admin.py
  pypro/modulos/facade.py
  pypro/modulos/migrations/0001_initial.py
  pypro/modulos/models.py
  pypro/settings.py
Labels: enhancement, backend, orm/database

#254 91
  .github/workflows/ci.yml
  pypro/modulos/admin.py
  pypro/modulos/migrations/0002_modulo_slug.py
  pypro/modulos/migrations/0003_populando_slug.py
  pypro/modulos/migrations/0004_slug_unico.py
  pypro/modulos/models.py
  pypro/modulos/tests/test_aba_de_modulos.py
Labels: enhancement, backend, migration issue, orm/database

#258 feat: cria página de detalhes do módulo com testes, view, facade e te…
  pypro/base/templates/base/home.html
  pypro/modulos/facade.py
  pypro/modulos/templates/modulos/modulo_detalhe.html
  pypro/modulos/tests/test_modulo_detalhe.py
  pypro/modulos/views.py
Labels: enhancement, backend, frontend, testing, orm/database

#260 94
  .github/workflows/ci.yml
  pypro/modulos/admin.py
  pypro/modulos/facade.py
  pypro/modulos/migrations/0005_aula.py
  pypro/modulos/models.py
  pypro/modulos/templates/modulos/modulo_detalhe.html
  pypro/modulos/tests/test_modulo_detalhe.py
  pypro/modulos/views.py
Labels: backend

#261 adicionado os links das aulas
  pypro/modulos/templates/modulos/modulo_detalhe.html
  pypro/modulos/tests/test_facade.py
  pypro/modulos/tests/test_modulo_detalhe.py
  pypro/modulos/urls.py
  pypro/modulos/views.py
Labels: enhancement, backend, testing

#262 criado as paginas de cada aula
  pypro/modulos/facade.py
  pypro/modulos/templates/modulos/aula_detalhe.html
  pypro/modulos/tests/test_aula_detalhe.py
  pypro/modulos/views.py
Labels: enhancement, backend, testing

#263 99
  pypro/modulos/migrations/0006_aula_video_id.py
  pypro/modulos/migrations/0007_alter_aula_video_id_obrigatorio.py
  pypro/modulos/models.py
  pypro/modulos/templates/modulos/aula_detalhe.html
  pypro/modulos/tests/test_aula_detalhe.py
Labels: enhancement, backend, orm/database

#264 navbar changed
  pypro/base/templates/base/base.html
Labels: enhancement, frontend

#272 inserido arrow buttons
  pypro/aperitivos/templates/aperitivos/video.html
  pypro/base/templates/base/base.html
  pypro/modulos/templates/modulos/aula_detalhe.html
Labels: frontend

#278 Implementado Aula.objects.select_related('modulo').get(slug=slug)
  pypro/modulos/facade.py
Labels: enhancement, backend, frontend, orm/database

#279 Implementado a feature de indice.html com testes
  pypro/modulos/templates/modulos/indice.html
  pypro/modulos/tests/test_modulos_indice.py
  pypro/modulos/urls.py
  pypro/modulos/views.py
Labels: enhancement, backend, frontend, testing

#282 Implementado o método prefetch _related para melhor performance
  pypro/modulos/facade.py
Labels: enhancement, backend, testing, orm/database

#286 108
  pypro/base/templates/base/home.html
  pypro/settings.py
  pypro/turmas/__init__.py
  pypro/turmas/admin.py
  pypro/turmas/apps.py
  pypro/turmas/migrations/__init__.py
  pypro/turmas/models.py
  pypro/turmas/tests/__init__.py
  pypro/turmas/tests/test_indice.py
  pypro/turmas/urls.py
  pypro/turmas/views.py
Labels: frontend

#287 inserido alguns icones
  pypro/base/templates/base/home.html
Labels: enhancement, frontend

#288 testes
  pypro/base/templates/base/home.html
  pypro/settings.py
  pypro/turmas/templates/indice.html
  pypro/turmas/views.py
  pypro/urls.py
Labels: enhancement, frontend

#290 test
  .gitattributes
  pypro/turmas/models.py
Labels: documentation, enhancement

#292 109
  pypro/turmas/admin.py
  pypro/turmas/migrations/0002_criação_matricula.py
  pypro/turmas/migrations/0003_restricao_de_matricula_unica.py
  pypro/turmas/models.py
Labels: enhancement, backend, testing, orm/database

#293 114
  pypro/base/templates/registration/login.html
  pypro/base/tests/test_login.py
  pypro/settings.py
  pypro/urls.py
Labels: enhancement, backend, frontend, testing

#294 PEP8 issues fixed
  pypro/base/templates/registration/login.html
  pypro/base/tests/test_login.py
Labels: testing

#298 122
  contrib/env-sample
  pypro/base/templates/registration/password_reset_done.html
  pypro/base/templates/registration/password_reset_form.html
  pypro/settings.py
Labels: enhancement, backend
